module.exports = {
  darkMode: 'class',
  content: [
    './*.html',         // all HTML in root
    './**/*.html',      // all HTML in subfolders
    './**/*.js'         // all JS templates if needed
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Open Sans', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
