/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './**/*.html', // if you also have standalone HTML files
  ],
  theme: {
    extend: {
      colors: {
        'custom-blue': '#1da1f2',        // main brand/accent color
        'custom-dark': '#0a0a0a',        // darker background
        'custom-light': '#f5f5f5',       // lighter background/text
        'custom-gray': '#6b7280',        // gray for secondary text
        'custom-highlight': '#ffcc00',   // highlight/yellow accents
      },
      fontFamily: {
        'sans': ['Roboto', 'sans-serif'], // main font
        'heading': ['Open Sans', 'sans-serif'], // optional heading font
      },
    },
  },
  plugins: [],
};
